### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by se7en-x230** [maaslalani/invoice#9]
1. How would I include a address with several lines?

2. How could I add a currency? DONE
I see the file and would add the currency + symbol but how would I compile it with the additional currency?
Recompiled it with my currency added and set as default. All good.

3. Also --date "June 10, 2023" does not print the date on the invoice.
Would it be possible to add the current date without typing it on the invoice? 
Something like --date current or similar even better set it in env?

**Comment by se7en-x230** [comment]
Some changes you made make it impossible to compile. 

![shop-2023-06-27-11-30](https://github.com/maaslalani/invoice/assets/69777713/e80b2b4f-b215-4a81-ab2a-88feba84b107)

**Comment by maaslalani** [comment]
<img width="898" alt="image" src="https://github.com/maaslalani/invoice/assets/42545625/17d0b00a-0f5e-499b-9f44-c48c43ab5bdf">

Hey @se7en-x230, I'm not able to reproduce. Can you try the following:

```
go clean -modcache -cache
go install .
```

**Comment by se7en-x230** [comment]
Thanks 
go clean -modcache -cache 
Did work

**Comment by se7en-x230** [comment]
I use dmenu to collect the infos like --to --date --item ...  
Fast, easy and the result looks good.

![shop-2023-06-27-19-52](https://github.com/maaslalani/invoice/assets/69777713/4d3bdbf8-76a3-490b-a489-95f9ee7ef099)

Thanks

**Comment by akyag** [comment]
I am trying to add common options to json. How do I add multiple items with different quantity/prices to the json?

**Comment by dvrd** [comment]
@se7en-x230 you can do something like this in `pdf.go`

```
func writeNotes(pdf *gopdf.GoPdf, notes string) {
	pdf.SetY(650)

	_ = pdf.SetFont("Inter", "", 10)
	pdf.SetTextColor(55, 55, 55)
	_ = pdf.Cell(nil, "Notes")
	pdf.Br(18)
	_ = pdf.SetFont("Inter", "", 8)
	pdf.SetTextColor(0, 0, 0)

	notesArr := strings.Split(notes, "\\n")

	for i := 0; i < len(notesArr); i++ {
		_ = pdf.Cell(nil, notesArr[i])
		pdf.Br(15)
	}
	pdf.Br(48)
}
```

**Comment by se7en-x230** [comment]
./pdf.go:103:14: undefined: strings

![shop-2023-06-29-08-07](https://github.com/maaslalani/invoice/assets/69777713/4d08bef5-9514-4080-9c2f-c839846ed6ab)

**Comment by se7en-x230** [comment]
works fine

--from --to and --notes should have the possibility for multiple lines

**Comment by maaslalani** [comment]
> I am trying to add common options to json. How do I add multiple items with different quantity/prices to the json?

@akyag You can do something like the following:

```yaml
{
	"items": ["Item 1", "Item 2", "Item 3"],
	"rates": [1, 2, 3],
	"quantities": [1, 2, 3]
}
```

**Comment by piotryordanov** [comment]
can the `notes` section be multiline?
I'm trying to add wire info toit, and it gets all on a single line instead of multi-line.

I tried adding both `<br/>` and `\\n` and `\n` but nothing seems to do the job

**Comment by piotryordanov** [comment]
@dvrd awesome!
Please let me know when this gets merged
